### ISSUE TITLE
The app doesn't detect accelerometer on Xiaomi Redmi Note 10 Pro

### ISSUE THREAD

**Issue by 0Fox** [abb128/owoTrackVRSyncMobile#1]
I'm using Xiaomi Redmi Note 10 Pro, the app can only see Rotation Sensor and Magnetometer.
![image](https://user-images.githubusercontent.com/24230448/228687550-a3b6d312-1bed-4845-8078-b42448ec2248.png)

The phone actually has an accelerometer ([gsmarena](https://www.gsmarena.com/xiaomi_redmi_note_10_pro-10662.php)), but the app for some reason cannot see it.

**Comment by abb128** [comment]
The home screen was updated to only show Rotation Sensor and Magnetometer to reduce confusion, it does not show or check for linear accelerometer anymore

**Comment by 0Fox** [comment]
@abb128 In SteamVR the tracker does not move tho, only rotates, is this how it's supposed to be?

**Comment by abb128** [comment]
@0Fox Are you using SlimeVR server or the old owotrack overlay?

The phone or Slime trackers don't track their 3D position in space, they only track the rotation. SlimeVR server uses that with forward kinematics to derive positions based on your HMD position. This sounds like a configuration issue on the PC side, as the app's sole job is to send rotation information which appears to be working in your case

**Comment by 0Fox** [comment]
@abb128 I'm using the old owotrack overlay, since I have only 1 phone and as far as I understand I can't use SlimeVR server without 5 phones.

**Comment by abb128** [comment]
You can definitely use SlimeVR Server with 1 phone, 2 phones or any number of phones. Anyway it sounds like maybe the Use Device Space option got unticked in the overlay, try making sure it's ticked

**Comment by 0Fox** [comment]
Oh, it was unticked! Thank you for help and quick replies
